### ISSUE TITLE
Cannot edit attached files after sufia7 update

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#406]
Error log `NoMethodError - undefined method `has?' for #<FileSet:0x007fd6518fd840>:
  activemodel (4.2.6) lib/active_model/attribute_methods.rb:433:in `method_missing'
  blacklight (6.3.1) app/helpers/blacklight/catalog_helper_behavior.rb:221:in `thumbnail_url'
  curation_concerns (1.1.2) app/views/curation_concerns/file_sets/media_display/_image.html.erb:4:in `block in __bundle_ruby_______gems_curation_concerns_______app_views_curation_concerns_file_sets_media_display__image_html_erb__3072096438466145322_70279223777760'
  actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
  haml (4.0.7) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
  actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
  actionview (4.2.6) lib/action_view/helpers/tag_helper.rb:106:in `content_tag'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:61:in `content_tag_with_haml'
  actionview (4.2.6) lib/action_view/helpers/url_helper.rb:184:in `link_to'
  curation_concerns (1.1.2) app/views/curation_concerns/file_sets/media_display/_image.html.erb:2:in `__bundle_ruby_______gems_curation_concerns_______app_views_curation_concerns_file_sets_media_display__image_html_erb__3072096438466145322_70279223777760'`

**Comment by njaffer** [comment]
done in sufia7_update branch
